name: pop_overlay
description: "A feature-rich package for displaying customizable pop-ups from any given widget. Featuring animated, draggable overlays, with optional background blur effects..."
repository: https://github.com/SoundSliced/pop_overlay
issue_tracker: https://github.com/SoundSliced/pop_overlay/issues
version: 3.1.1
homepage: https://github.com/SoundSliced/pop_overlay

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  s_packages: ^1.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  # Explicitly specify supported platforms
platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:
